// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAttribute(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddAttribute'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddBigProcess(arg1, arg2) {
  return window['go']['main']['App']['AddBigProcess'](arg1, arg2);
}

export function AddEntity(arg1, arg2) {
  return window['go']['main']['App']['AddEntity'](arg1, arg2);
}

export function AddIntersectionAttribute(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddIntersectionAttribute'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProcess'](arg1, arg2, arg3);
}

export function AddRelation(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRelation'](arg1, arg2, arg3);
}

export function AddResource(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddResource'](arg1, arg2, arg3, arg4, arg5);
}

export function AddRole(arg1, arg2) {
  return window['go']['main']['App']['AddRole'](arg1, arg2);
}

export function AddRoleProcessPermission(arg1, arg2) {
  return window['go']['main']['App']['AddRoleProcessPermission'](arg1, arg2);
}

export function AddRoleTablePermission(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddRoleTablePermission'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddStep(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddStep'](arg1, arg2, arg3, arg4);
}

export function CreateExcelPath() {
  return window['go']['main']['App']['CreateExcelPath']();
}

export function CreateExcelPathWithoutRelations() {
  return window['go']['main']['App']['CreateExcelPathWithoutRelations']();
}

export function CreateNew(arg1, arg2) {
  return window['go']['main']['App']['CreateNew'](arg1, arg2);
}

export function CreateProjectJSONPath() {
  return window['go']['main']['App']['CreateProjectJSONPath']();
}

export function EditAttribute(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['EditAttribute'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function EditBigProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditBigProcess'](arg1, arg2, arg3);
}

export function EditEntity(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditEntity'](arg1, arg2, arg3);
}

export function EditIntersectionAttribute(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['EditIntersectionAttribute'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function EditIntersectionEntityDescription(arg1, arg2) {
  return window['go']['main']['App']['EditIntersectionEntityDescription'](arg1, arg2);
}

export function EditProcess(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditProcess'](arg1, arg2, arg3, arg4);
}

export function EditResource(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['EditResource'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function EditRole(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditRole'](arg1, arg2, arg3);
}

export function EditRoleProcessPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditRoleProcessPermission'](arg1, arg2, arg3);
}

export function EditRoleTablePermission(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['EditRoleTablePermission'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function EditStep(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EditStep'](arg1, arg2, arg3, arg4, arg5);
}

export function EjectProject() {
  return window['go']['main']['App']['EjectProject']();
}

export function ExportCombinationsToExcel(arg1) {
  return window['go']['main']['App']['ExportCombinationsToExcel'](arg1);
}

export function ExportEntitiesToJSON(arg1, arg2) {
  return window['go']['main']['App']['ExportEntitiesToJSON'](arg1, arg2);
}

export function ExportToExcel(arg1) {
  return window['go']['main']['App']['ExportToExcel'](arg1);
}

export function GenerateSQLFromEntities(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateSQLFromEntities'](arg1, arg2, arg3);
}

export function GetAISettings() {
  return window['go']['main']['App']['GetAISettings']();
}

export function GetActualProject() {
  return window['go']['main']['App']['GetActualProject']();
}

export function GetCombinatory() {
  return window['go']['main']['App']['GetCombinatory']();
}

export function GetEntity(arg1) {
  return window['go']['main']['App']['GetEntity'](arg1);
}

export function GetIntersectionEntityByRelationID(arg1) {
  return window['go']['main']['App']['GetIntersectionEntityByRelationID'](arg1);
}

export function GetRelationTypes() {
  return window['go']['main']['App']['GetRelationTypes']();
}

export function GetRole(arg1) {
  return window['go']['main']['App']['GetRole'](arg1);
}

export function IntersectionHasAttributes(arg1) {
  return window['go']['main']['App']['IntersectionHasAttributes'](arg1);
}

export function MarkEntityStatus(arg1, arg2) {
  return window['go']['main']['App']['MarkEntityStatus'](arg1, arg2);
}

export function MoveAttribute(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveAttribute'](arg1, arg2, arg3);
}

export function MoveBigProcess(arg1, arg2) {
  return window['go']['main']['App']['MoveBigProcess'](arg1, arg2);
}

export function MoveEntity(arg1, arg2) {
  return window['go']['main']['App']['MoveEntity'](arg1, arg2);
}

export function MoveIntersectionAttribute(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveIntersectionAttribute'](arg1, arg2, arg3);
}

export function MoveProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveProcess'](arg1, arg2, arg3);
}

export function MoveStep(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveStep'](arg1, arg2, arg3, arg4);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PickProjectJSON() {
  return window['go']['main']['App']['PickProjectJSON']();
}

export function RemoveAttribute(arg1, arg2) {
  return window['go']['main']['App']['RemoveAttribute'](arg1, arg2);
}

export function RemoveBigProcess(arg1) {
  return window['go']['main']['App']['RemoveBigProcess'](arg1);
}

export function RemoveEntity(arg1) {
  return window['go']['main']['App']['RemoveEntity'](arg1);
}

export function RemoveIntersectionAttribute(arg1, arg2) {
  return window['go']['main']['App']['RemoveIntersectionAttribute'](arg1, arg2);
}

export function RemoveProcess(arg1, arg2) {
  return window['go']['main']['App']['RemoveProcess'](arg1, arg2);
}

export function RemoveRelation(arg1) {
  return window['go']['main']['App']['RemoveRelation'](arg1);
}

export function RemoveResource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RemoveResource'](arg1, arg2, arg3, arg4);
}

export function RemoveRole(arg1) {
  return window['go']['main']['App']['RemoveRole'](arg1);
}

export function RemoveRoleProcessPermission(arg1, arg2) {
  return window['go']['main']['App']['RemoveRoleProcessPermission'](arg1, arg2);
}

export function RemoveRoleTablePermission(arg1, arg2) {
  return window['go']['main']['App']['RemoveRoleTablePermission'](arg1, arg2);
}

export function RemoveStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveStep'](arg1, arg2, arg3);
}

export function Save() {
  return window['go']['main']['App']['Save']();
}

export function SaveOpenAIAPIKey(arg1) {
  return window['go']['main']['App']['SaveOpenAIAPIKey'](arg1);
}
