// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function GetCombinatory():Promise<Array<utils.RelationView>>;

export function Greet(arg1:string):Promise<string>;

export function OpenPath(arg1:string):Promise<utils.DbProject>;

export function PickProjectJSON():Promise<string>;
