// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';

export function AddAttribute(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddEntity(arg1:string,arg2:string):Promise<void>;

export function AddRelation(arg1:number,arg2:number,arg3:string):Promise<void>;

export function CreateExcelPath():Promise<string>;

export function CreateNew(arg1:string,arg2:string):Promise<utils.DbProject>;

export function CreateProjectJSONPath():Promise<string>;

export function EditAttribute(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function EditEntity(arg1:number,arg2:string,arg3:string):Promise<void>;

export function EjectProject():Promise<void>;

export function ExportToExcel(arg1:string):Promise<void>;

export function GetActualProject():Promise<utils.DbProject>;

export function GetCombinatory():Promise<Array<utils.RelationView>>;

export function GetEntity(arg1:number):Promise<utils.Entity>;

export function MarkEntityStatus(arg1:number,arg2:boolean):Promise<void>;

export function MoveAttribute(arg1:number,arg2:number,arg3:string):Promise<void>;

export function MoveEntity(arg1:number,arg2:string):Promise<void>;

export function OpenPath(arg1:string):Promise<utils.DbProject>;

export function PickProjectJSON():Promise<string>;

export function RemoveAttribute(arg1:number,arg2:number):Promise<void>;

export function RemoveEntity(arg1:number):Promise<void>;

export function RemoveRelation(arg1:number):Promise<void>;

export function Save():Promise<void>;
