// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntity(arg1, arg2) {
  return window['go']['main']['App']['AddEntity'](arg1, arg2);
}

export function AddRelation(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRelation'](arg1, arg2, arg3);
}

export function CreateNew(arg1) {
  return window['go']['main']['App']['CreateNew'](arg1);
}

export function CreateProjectJSONPath() {
  return window['go']['main']['App']['CreateProjectJSONPath']();
}

export function EditEntity(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditEntity'](arg1, arg2, arg3);
}

export function EjectProject() {
  return window['go']['main']['App']['EjectProject']();
}

export function GetActualProject() {
  return window['go']['main']['App']['GetActualProject']();
}

export function GetCombinatory() {
  return window['go']['main']['App']['GetCombinatory']();
}

export function GetEntity(arg1) {
  return window['go']['main']['App']['GetEntity'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PickProjectJSON() {
  return window['go']['main']['App']['PickProjectJSON']();
}

export function RemoveEntity(arg1) {
  return window['go']['main']['App']['RemoveEntity'](arg1);
}

export function RemoveRelation(arg1) {
  return window['go']['main']['App']['RemoveRelation'](arg1);
}

export function Save() {
  return window['go']['main']['App']['Save']();
}
